---
- name: backup router configurations
  hosts: routers
  connection: local

  tasks:
    - name: grab running configuration
      ios_command:
        commands:
          - show run
      register: config

    - name: save output to backups directory
      copy:
        content: "{{config.stdout[0]}}"
        dest: "backups/show_run_{{inventory_hostname}}.txt"
