---
- name: R1 gre configuration
  hosts: student1-rtr1.net-ws.redhatgov.io
  gather_facts: no

  tasks:
    - name: create tunnel interface to R2
      ios_config:
        lines:
         - ip address 10.0.0.1 255.255.255.0
         - tunnel source GigabitEthernet1
         - tunnel destination 52.15.93.123
        parents: interface Tunnel 0


- name: R2 gre configuration
  hosts: student1-rtr2.net-ws.redhatgov.io
  gather_facts: no

  tasks:

    - name: create tunnel interface to R1
      ios_config:
        lines:
         - ip address 10.0.0.2 255.255.255.0
         - tunnel source GigabitEthernet1
         - tunnel destination 18.220.223.21
        parents: interface Tunnel 0
