---
- name: enable interface if R2 is compliant
  hosts: student1-rtr2.net-ws.redhatgov.io
  connection: local

  tasks:
    - name: capture show version
      ios_command:
        commands:
          - show version
      register: version

    - name: shutdown GigabitEthernet2 if not compliant
      net_interface:
        name: GigabitEthernet2
        description: not-compliant
        state: down
      when: not 'Version 16.5.1b' in version.stdout[0]

    - block:
      - name: enable GigabitEthernet2 interface if compliant
        net_interface:
          name: GigabitEthernet2
          description: interface to host1

      - name: dhcp configuration for GigabitEthernet2
        ios_config:
          lines:
            - ip address dhcp
          parents: interface GigabitEthernet2

      when: '"Version 16.5.1b" in version.stdout[0]'
