---
- name: enable interface if R2 is compliant
  hosts: student1-rtr2.net-ws.redhatgov.io
  connection: local
  gather_facts: no

  tasks:
    - name: gather ios_facts
      ios_facts:
      register: version

    - debug:
        msg: "{{version}}"

    - name: shutdown GigabitEthernet2 if not compliant
      net_interface:
        name: GigabitEthernet2
        description: not-compliant
        state: down
      when: not version.ansible_facts.ansible_net_version == "16.5.1b"

    - block:
      - name: enable GigabitEthernet2 interface if compliant
        net_interface:
          name: GigabitEthernet2
          description: interface to host1

      - name: dhcp configuration for GigabitEthernet2
        ios_config:
          lines:
            - ip address dhcp
          parents: interface GigabitEthernet2

      when: version.ansible_facts.ansible_net_version == "16.5.1b"
