---
- name: Router Configurations
  hosts: routers
  gather_facts: no
  connection: local
  vars:
    dns_servers:
      - 8.8.8.8
      - 8.8.4.4
  tasks:
    - name: gather ios_facts
      ios_facts:
      register: version

    ##Configuration for R1
    - block:
      - name: Static route from R1 to R2
        ios_config:
          lines:
            - ip route "{{prefix_host_subnet}}" 255.255.255.0 10.0.0.2
      - name: configure name servers
        net_system:
          name_servers: "{{item}}"
        with_items: "{{dns_servers}}"
      when:
        - 'version.ansible_facts.ansible_net_version == "{{ios_version}}"'
        - '"rtr1" in inventory_hostname'

    ##Configuration for R2
    - block:
      - name: enable GigabitEthernet2 interface if compliant
        net_interface:
          name: GigabitEthernet2
          description: interface to host1
          state: present
      - name: dhcp configuration for GigabitEthernet2
        ios_config:
          lines:
            - ip address dhcp
          parents: interface GigabitEthernet2
      - name: Static route from R2 to R1
        net_static_route:
        ios_config:
          lines:
            - ip route "{{prefix_control_subnet}}" 255.255.255.0 10.0.0.1
      - name: configure name servers
        net_system:
          name_servers: "{{item}}"
        with_items: "{{dns_servers}}"
      when:
        - 'version.ansible_facts.ansible_net_version == "{{ios_version}}"'
        - '"rtr2" in inventory_hostname'
